# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_covSAM <- function(X) {
    .Call('_coper_cpp_covSAM', PACKAGE = 'coper', X)
}

cpp_cov2pcor <- function(Sigma) {
    .Call('_coper_cpp_cov2pcor', PACKAGE = 'coper', Sigma)
}

